# Generated by Django 2.1.3 on 2018-11-11 08:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='名字')),
                ('country', models.CharField(default='', max_length=20, verbose_name='国家')),
                ('docs', models.CharField(default='', help_text='简介', max_length=2500, verbose_name='简介')),
                ('representative_work', models.CharField(default='', help_text='代表作', max_length=100, verbose_name='代表作')),
            ],
            options={
                'verbose_name': '作者信息',
                'verbose_name_plural': '作者信息',
            },
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='类别名', max_length=50, verbose_name='类别名')),
                ('code', models.CharField(default='', help_text='类别code', max_length=50, verbose_name='类别code')),
                ('desc', models.CharField(default='', help_text='类别描述', max_length=100, verbose_name='类别描述')),
                ('category_type', models.IntegerField(choices=[(1, '一级类目'), (2, '二级类目'), (3, '三级类目'), (4, '四级类目')], help_text='类目级别', verbose_name='类目级别')),
                ('is_tab', models.BooleanField(default=False, help_text='是否导航', verbose_name='是否导航')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('parent_category', models.ForeignKey(blank=True, help_text='父目录', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='books.BookCategory', verbose_name='父类目级别')),
            ],
            options={
                'verbose_name': '书籍类别',
                'verbose_name_plural': '书籍类别',
            },
        ),
        migrations.CreateModel(
            name='BookDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.IntegerField(default=0, unique=True, verbose_name='章节编号')),
                ('docs', models.CharField(choices=[(1, '章节标题'), (2, '章节内容')], default='', max_length=100, verbose_name='章节类型')),
            ],
            options={
                'verbose_name': '书籍信息',
                'verbose_name_plural': '书籍信息',
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_sn', models.CharField(default='', help_text='书籍唯一编号', max_length=100, verbose_name='书籍唯一编号')),
                ('name', models.CharField(help_text='书籍名字', max_length=50, verbose_name='书籍名字')),
                ('goods_front_image', models.ImageField(blank=True, help_text='封面图', null=True, upload_to='books/images/', verbose_name='封面图')),
                ('docs', models.CharField(default='', help_text='简介', max_length=2500, verbose_name='简介')),
                ('is_new', models.BooleanField(default=False, verbose_name='是否新品')),
                ('is_hot', models.BooleanField(default=False, verbose_name='是否热销')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(help_text='作者', on_delete=django.db.models.deletion.CASCADE, to='books.BookAuthor', verbose_name='作者')),
                ('category', models.ForeignKey(help_text='书籍类目', on_delete=django.db.models.deletion.CASCADE, to='books.BookCategory', verbose_name='书籍类目')),
            ],
            options={
                'verbose_name': '书籍信息',
                'verbose_name_plural': '书籍信息',
            },
        ),
        migrations.CreateModel(
            name='PublishInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='出版社', max_length=100, verbose_name='出版社')),
                ('original_name', models.CharField(default='', help_text='原作名', max_length=50, verbose_name='原作名')),
                ('translator', models.CharField(default='', help_text='译者', max_length=50, verbose_name='译者')),
                ('publication_year', models.DateField(default='', help_text='出版年', verbose_name='出版年')),
                ('page_num', models.IntegerField(default=0, help_text='页数', verbose_name='页数')),
                ('price', models.FloatField(default=0, help_text='定价', verbose_name='定价')),
                ('Binding', models.CharField(default='平装', help_text='装帧类型', max_length=20, verbose_name='装帧类型')),
                ('isbn', models.CharField(default='', help_text='ISBN', max_length=50, verbose_name='ISBN')),
                ('author', models.ForeignKey(default='', help_text='作者', max_length=100, on_delete=django.db.models.deletion.CASCADE, to='books.BookAuthor', verbose_name='作者')),
            ],
            options={
                'verbose_name': '出版社信息',
                'verbose_name_plural': '出版社信息',
            },
        ),
        migrations.AddField(
            model_name='books',
            name='publish_information',
            field=models.ForeignKey(help_text='出版信息', on_delete=django.db.models.deletion.CASCADE, to='books.PublishInformation', verbose_name='出版信息'),
        ),
        migrations.AddField(
            model_name='bookdetail',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Books', verbose_name='书籍ID'),
        ),
    ]
