# Generated by Django 2.1.3 on 2018-11-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='price',
            field=models.FloatField(default=0, help_text='售价', verbose_name='售价'),
        ),
    ]
